spring:
  application:
    name: spf-msa-account
  header:
    channel: digital
    medium: web
  web-flux:
    base-path: /technical-test/v1
  profiles:
    active:
      - development
backend:
  time:
    session: 100