server:
  port: 80
  error:
    include-message: always

info:
  project:
    name: spf-msa-async-customer
    version: 1.0.0

spring:
  data:
    redis:
      host: redis
      port: 6379

client:
  http-client:
    baseUrl: http://account-client:80/technical-test/v1/accounts